### ISSUE TITLE
cache will exit with exception when restore from broken ones.

### ISSUE THREAD

**Issue by wuhuizuo** [j3t/jenkins-pipeline-cache-plugin#16]
## my pipeline (only the important part)
![ynHtTdrr52](https://user-images.githubusercontent.com/2574558/184632294-0bd78030-a4e2-46e7-9972-e78f307875ff.png)

## the MinIO S3 object
![BPb0WuavIr](https://user-images.githubusercontent.com/2574558/184633458-221e5a1e-fd3d-4a65-92f6-b9a2e45c0758.png)

## issue description

- it's better to display cache steps on blue ocean view
   > ![HgJQO6UO1b](https://user-images.githubusercontent.com/2574558/184632517-a72e2e6d-47a0-45a1-af7e-3e5b12745c18.png)
- should not failed when restore from a broken object(uploading was interrupted)
   > ![7HVM9cBZ3y](https://user-images.githubusercontent.com/2574558/184632745-97e8e23c-ca3d-49de-b61a-773aaf5c2123.png) ![SJBETiC56F](https://user-images.githubusercontent.com/2574558/184632769-3d985347-4c9e-47ab-9c06-d027f354156e.png)

**Comment by j3t** [comment]
Since the main problem is that a corrupted tar archive was uploaded, we should focus on that part first. I guess we can make the upload process more stable so that only valid archives are visible in the end. Do you have the error message from the failed upload as well?

**Comment by wuhuizuo** [comment]
> 
no error found

**Comment by j3t** [comment]
The plugin will still fail if a corrupted tar archive is restored but with #17 the problem that corrupted files are uploaded to S3 is almost zero.
