### ISSUE TITLE
doc / question: does filter: '**/*' turn off the default excludes?

### ISSUE THREAD

**Issue by rbtcollins** [j3t/jenkins-pipeline-cache-plugin#31]
Thats it really - does filter: '**/*' turn off the default excludes? - the docs left me unclear on this point. (I need to cache a .git dir in ~/.cargo...)

**Comment by j3t** [comment]
Yes, when a custom filter is defined then the [default excludes](https://ant.apache.org/manual/dirtasks.html#defaultexcludes) are not applied anymore.

**Comment by j3t** [comment]
tbh, I'm not sure about the existing filter property. Maybe a separate include and exclude property would be more sufficient, but then I would also turn of the [default excludes](https://ant.apache.org/manual/dirtasks.html#defaultexcludes).

* include (default: **/*) 
* exclude (default: null)
