### ISSUE TITLE
 Cache not saved (path not exists) for path in a container

### ISSUE THREAD

**Issue by rbtcollins** [j3t/jenkins-pipeline-cache-plugin#32]
(Sorry for all the bug/discussions!)
We use the jenkins kubernetes plugin. That provides a step [container](https://www.jenkins.io/doc/pipeline/steps/kubernetes/#container-run-build-steps-in-a-container) that causes shell steps to run in the container. 
However the `cache` step seems to not have access to the filesystem in that container. 

This matters when caching `cargo` global state (the registry, downloaded packages, installed binaries) as they are in the `rust:<version>` container, so a step like this:
```
cache(path: '/usr/local/cargo', key: "${cache_key}-cargo", restoreKeys: [project_name], filter: '**/*') {
   ... build stuff here ...
}
```

doesn't ever get populated (and I presume restores would also fail too). 

I'm not sure what would be required to integrate with that plugin better - for now I'm going to manually make an archive copy of the directory into the workspace to cache it, but avoiding that would be great.

**Comment by j3t** [comment]
_Selects a container of the agent pod so that all shell steps are executed in that container._

I'm not familiar with the container step but according to the documentation it is limited to shell commands I guess. Is there any error/debug message available?

**Comment by rbtcollins** [comment]
I wouldn't know which log context to filter for in Jenkins, and the master is -very- busy. Nothing shows up in the job log itself.

**Comment by rbtcollins** [comment]
It should be very easy to test locally if you're interested : use [kind](https://kind.sigs.k8s.io/) or minikube or whatever, add the kubernetes plugin to your local jenkins, and then define a pod in a pipeline job - something like
```
podTemplate(
  containers: [containerTemplate(name: 'rust', image: 'rust:1.66.1', ttyEnabled: true,command: '/bin/cat -')],
) {
  node(POD_LABEL) {
    cache(path: '/usr/local/cargo', key: 'example') {
      echo "failure after this"
    }
  }
}
```

**Comment by j3t** [comment]
I guess at least one container in the pod must be a jenkins-agent. Could you please check your example with the `jenkins/inbound-agent image`?

_Agents are launched as inbound agents, so it is expected that the container connects automatically to the Jenkins controller. For that some environment variables are automatically injected:_

**Comment by rbtcollins** [comment]
Yes, its defined globally. https://plugins.jenkins.io/kubernetes/#plugin-content-configuration

**Comment by j3t** [comment]
I don't know exactly how the `container` step works, but it is very likely that the `cache` step is exectuted on the jnlp container rather than on the rust container. I guess you could workaround this by sharing a volume with all containers or when by operating on the workspace instead.

**Comment by rbtcollins** [comment]
They do share a EmptyDir volume (a transient directory on the kubernetes node) automatically, but the problem is the cargo cache contents need to come from a directory that is in one of the other images, so it is by definition not accessible to the `jnlp` container. The workaround we're using is to move that directory into the work space as one of the early steps in the build, and leave a symlink in its place. Then cache the dir from the workspace.
