### ISSUE TITLE
timeout with large cache

### ISSUE THREAD

**Issue by rbtcollins** [j3t/jenkins-pipeline-cache-plugin#35]
We have two separate dirs to cache (cargo again - so one is the CARGO_HOME and one is the project specific `target` directory).

To be quite honest, I'm not sure that caching the size of project specific files will end up making sense, I'm still working through the github logic to make sure I'm trimming all that I should. However, with that caveat:

backing up the CARGO_HOME succeeds:
```
Cache saved successfully (PROJECT_-cargo-d41d8cd98f00b204e9800998ecf8427e)
336728576 bytes in 44.30 secs (7601509 bytes/sec)
```

This is kindof slow: single request uploads within Google datacentres should get at least 100MBps, not 8MBps. E.g. see https://www.doit.com/optimize-data-transfer-between-compute-engine-and-cloud-storage/ which shows the bucket upload being ~80MBps for a single-request-upload.

Now, I'm sure there are lots of combined factors here, and I haven't studied your code enough to make suggestions. Well, I'll make one, having spent a bunch of time on similar systems in the past: 
* consider using a wire rate compression library (such as LZO or zstd) rather than gzip, which is (by comparison) horrifically slow
* rather than [up|down]loading from S3 to the master and then doing e.g. unTarFrom on the master, which performs masterToSlave IO (as far as I can tell from a quick glance), instead download or upload to S3 directly from the slave: remote an object to the slave to perform the task, and then the master will have no IO or computation load from the step.

These two things together should be able to dramatically increase performance, even without multipart uploads and the like.

And the clincher:  our `target` directory is 14GB, so at 200MBps that would be 70 seconds : not brilliant, but not terrible. At 8MBps it will be ~1500seconds - much longer than our current uncached builds take.

**Comment by j3t** [comment]
> consider using a wire rate compression library (such as LZO or zstd) rather than gzip, which is (by comparison) horrifically slow

we are using plain tar without any compression (see https://github.com/j3t/jenkins-pipeline-cache-plugin/blob/main/src/main/java/io/jenkins/plugins/pipeline/cache/agent/BackupCallable.java#L64), this was the fastest in my tests

btw, the time which is displayed includes the time for creating the archive and for creating the checksum as well.

> rather than [up|down]loading from S3 to the master and then doing e.g. unTarFrom on the master, which performs masterToSlave IO (as far as I can tell from a quick glance), instead download or upload to S3 directly from the slave: remote an object to the slave to perform the task, and then the master will have no IO or computation load from the step.

I'm pretty sure that the upload is done directly from the remote node to S3. The Callable's are created on the master node but they are executed on the remote node (see https://wiki.jenkins-ci.org/display/JENKINS/Making+your+plugin+behave+in+distributed+Jenkins).

Have you checked the upload speed from the remote node to S3/GCS?

**Comment by rbtcollins** [comment]
I'm going to close this - downloads are 200MBps and its possible the node was just having a bad day when I measured this. I'll reopen/make a new one if I can really narrow this down to my prior thoughts here.
